from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Action:
    """A candidate action generated by deterministic environment code."""

    id: str
    kind: str
    payload: dict[str, Any] = field(default_factory=dict)
